server:
  port: 8003

spring:
  application:
    name: server-user

  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://39.100.192.1:12345/feier?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8

    #配置日期格式 和时区
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8

  redis:
    host: 39.100.192.1
    port: 6379
    database: 0
    timeout: 18000
    lettuce:
      pool:
        max-active: 20
        max-wait: 1
        max-idle: 5
        min-idle: 0




  #引入mybatis配置文件
mybatis-plus:
  mapper-locations: classpath:com/feier/userServer/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl