server:
  port: 8002

spring:
  application:
    name: service-product
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://39.100.192.1:12345/feier?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8

#配置日期格式 和时区
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#引入mybatis配置文件
mybatis-plus:
  mapper-locations: classpath:com/feier/productServer/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl